server/auth.py
# auth.py

from flask import Blueprint, render_template, redirect, url_for, request, flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required
from .models import User
from . import db

auth = Blueprint('auth', __name__)

@auth.route('/login')
def login():
    return render_template('login.html')

@auth.route('/login', methods=['POST'])
def login_post():
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    user = User.query.filter_by(email=email).first()

    # check if user actually exists
    # take the user supplied password, hash it, and compare it to the hashed password in database
    if not user or not check_password_hash(user.password, password): 
        flash('Please check your login details and try again.')
        return redirect(url_for('auth.login')) # if user doesn't exist or password is wrong, reload the page

    # if the above check passes, then we know the user has the right credentials
    login_user(user, remember=remember)
    return redirect(url_for('main.profile'))

@auth.route('/signup')
def signup():
    return render_template('signup.html')

@auth.route('/signup', methods=['POST'])
def signup_post():

    email = request.form.get('email')
    name = request.form.get('name')
    password = request.form.get('password')

    user = User.query.filter_by(email=email).first() # if this returns a user, then the email already exists in database

    if user: # if a user is found, we want to redirect back to signup page so user can try again  
        flash('Email address already exists')
        return redirect(url_for('auth.signup'))

    # create new user with the form data. Hash the password so plaintext version isn't saved.
    new_user = User(email=email, name=name, password=generate_password_hash(password, method='sha256'))

    # add the new user to the database
    db.session.add(new_user)
    db.session.commit()

    return redirect(url_for('auth.login'))

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

server/controller/main.py
# main.py
import json
import os

from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user, login_manager
from flask import current_app as app
from sqlalchemy import select
from werkzeug.utils import secure_filename

from server.controller.nn_tools import get_predictions
from server.model.models import Summary, SampleSummary
from server import db

main = Blueprint('main', __name__)


# @main.route('/')
# @login_required
# def index():
#     return render_template('index.html')


@main.route('/profile')
@login_required
def profile():
    return render_template('profile.html', name=current_user.name)


@main.route('/', methods=['POST'])
@login_required
def upload_file():
    if request.method == 'POST':
        # check if the post request has the file part
        if 'file' not in request.files:
            flash('No file part')
            return redirect(request.url)
        file = request.files['file']
        # if user does not select file, browser also
        # submit an empty part without filename
        if file.filename == '':
            flash('No selected file')
            return redirect(request.url)
        if file:
            filename = secure_filename(file.filename)
            file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
            summary = get_predictions(os.path.join(app.config['UPLOAD_FOLDER'],filename))
            return redirect(url_for('main.upload_summary',
                                    summary=summary, filename=filename))
    return render_template('index.html')


@main.route('/', methods=['GET'])
@login_required
def index():
    id = current_user.id
    summary = Summary.query.filter_by(user_id=id).all()
    return render_template('index.html', summary=summary)


@main.route('/upload_summary/<string:summary>/<string:filename>')
@login_required
def upload_summary(summary, filename):
    j = json.loads(summary)
    emotions=['neutral', 'happy', 'sad', 'hate', 'anger']
    neutral = j['counts']['0']
    happy = j['counts']['1']
    sad = j['counts']['2']
    hate = j['counts']['3']
    anger = j['counts']['4']
    pr = j['predictions']
    new_summary = Summary(user_id=current_user.id,name=filename, hate_cnt=hate, neutal_cnt=neutral, happy_cnt=happy, sad_cnt=sad, anger_cnt=anger)
    db.session.add(new_summary)
    db.session.commit()
    print(new_summary.id)
    print(pr)
    for i in range(len(pr)):
        new_sample_summary = SampleSummary(summary_id=new_summary.id, neutral=pr[i][0][0],
                                           happy=pr[i][0][1], sad=pr[i][0][2], hate=pr[i][0][3], anger=pr[i][0][4])
        db.session.add(new_sample_summary)
    db.session.commit()
    return render_template('summary.html', emotions=emotions, happy=happy, neutral=neutral, sad=sad,hate=hate, anger=anger, pr=pr)


@main.route('/load_summary_by_id/<int:id>')
@login_required
def load_summary_by_id(id):
    j = Summary.query.filter_by(id=id).first()
    emotions=['neutral', 'happy', 'sad', 'hate', 'anger']
    neutral = j.neutal_cnt
    happy = j.happy_cnt
    sad = j.sad_cnt
    hate = j.hate_cnt
    anger = j.anger_cnt
    sample_summaries = SampleSummary.query.filter_by(summary_id=id).all()
    pr=[]
    for sample in sample_summaries:
        arr = [[sample.neutral, sample.happy, sample.sad, sample.hate, sample.anger]]
        pr.append(arr)
    return render_template('summary.html', emotions=emotions, happy=happy, neutral=neutral, sad=sad,hate=hate, anger=anger, pr=pr)

server/templates/base.html
<!-- templates/base.html -->

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Emotion detector</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
</head>

<body>
    <section class="hero is-light is-fullheight">
        <section class="hero is-primary">
        <div class="hero-head">
            <nav class="navbar">
                <div class="container">

                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
                            <a href="{{ url_for('main.index') }}" class="navbar-item">
                                Home
                            </a>
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('main.profile') }}" class="navbar-item">
                                Profile
                            </a>
                            {% endif %}
                            {% if not current_user.is_authenticated %}
                            <a href="{{ url_for('auth.login') }}" class="navbar-item">
                                Login
                            </a>
                            <a href="{{ url_for('auth.signup') }}" class="navbar-item">
                                Sign Up
                            </a>
                            {% endif %}
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('auth.logout') }}" class="navbar-item">
                                Logout
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </div>
        </section>
        <div class="hero-body ">
            <div class="container has-text-centered">
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </section>
</body>

</html>

server/templates/index.html
<!-- templates/index.html -->

{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Get detailed summary of emotions for your product
</h1>
<h2 class="subtitle">
  Just load file with comments:
</h2>
<form method=post enctype=multipart/form-data>
      <input type=file name=file>
      <input type=submit value=Upload>
</form>
<h1 class="title" style="margin-top: 100px">
  Or choose previous summary
</h1>
<table  align="center" style="margin: 0px auto;">
    <tr>
        <th>id</th>
        <th>name</th>
        <th>timestamp</th>
    </tr>
    <colgroup>
    {% for _ in range(2) %}
        <col style="width: 205px">
    {% endfor %}
         <col style="width: 305px">
    </colgroup>
{% for s in summary %}
    <tr >
        <td ><a href="{{ url_for('main.load_summary_by_id', id=s['id']) }}">{{s['id']}}</a></td>
        <td>{{s['name']}}</td>
        <td>{{s['timestamp']}}</td>
    </tr>
{% endfor %}
</table>
{% endblock %}

server/templates/login.html
<!-- templates/login.html -->

{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Login</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}
            </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/login">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Your Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Your Password">
                </div>
            </div>
            <div class="field">
                <label class="checkbox">
                    <input type="checkbox">
                    Remember me
                </label>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Login</button>
        </form>
    </div>
</div>
{% endblock %}

server/templates/profile.html
<!-- templates/profile.html -->

{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Welcome, {{ name }}!
</h1>
{% endblock %}

server/templates/signup.html
<!-- templates/signup.html -->

{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Sign Up</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}. Go to <a href="{{ url_for('auth.login') }}">login page</a>.
            </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/signup">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="name" placeholder="Name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Password">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Sign Up</button>
        </form>
    </div>
</div>
{% endblock %}

server/templates/summary.html
<!-- templates/index.html -->

{% extends "base.html" %}

{% block content %}
<div style="display: inline-block; margin: 40px">
  <img src="/static/neutral.png" height="120px" width="120px">
    <h1 style="font-size: 50px">{{ neutral }}</h1>
</div>
<div style="display: inline-block; margin: 40px">
  <img src="/static/happy.png" height="120px" width="120px">
    <h1 style="font-size: 50px">{{ happy }}</h1>
</div>
<div style="display: inline-block; margin: 40px">
  <img src="/static/sad.png" height="120px" width="120px">
    <h1 style="font-size: 50px">{{ sad }}</h1>
</div>
<div style="display: inline-block; margin: 40px">
  <img src="/static/hate.png" height="120px" width="120px">
    <h1 style="font-size: 50px">{{ hate }}</h1>
</div>
<div style="display: inline-block; margin: 40px">
  <img src="/static/anger.png" height="120px" width="120px">
    <h1 style="font-size: 50px">{{ anger }}</h1>
</div>
<table style="margin-left: 40px">
    <tr>
        <th>id</th>
        {% for e in emotions %}
        <th> {{ e }} </th>
        {% endfor %}
    </tr>
    <colgroup>
    {% for _ in range(6) %}
        <col style="width: 205px">
    {% endfor %}
    </colgroup>
    <tbody>
        {% for i in range(pr|length) %}
        <tr>
            <td>{{i}}</td>
            {% for p in pr[i][0]%}
            <td>{{p}}</td>
            {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}